### ISSUE TITLE
MBx_Ticks函数的传参理解

### ISSUE THREAD

**Issue by dmzy007** [stbanana/modbusX#4]
刚开始使用的时候，MBx_Ticks的参数Cycle值应该填多少，让我一直很困惑。

摸索了一段时间后，总算是给整明白了

MBx_Ticks的参数Cycle是一个时间常数，单位是us。

MBx_Ticks需要周期性进行调用，如果调用MBx_Ticks的时间周期是1ms，那么参数Cycle的值就应该是1000；如果调用MBx_Ticks的时间周期是500us，那么参数Cycle的值就应该是500。

**Comment by stbanana** [comment]
文档和示例中都写的比较清楚，使用前请仔细阅读文档。

[MBx_Ticks](https://wiki.yono233.cn/modbusX/zh_hans/apidoc/apigengric/MBx_Ticks.html)

```c
MBx_Ticks(1000);  // 换算为微秒传入MBx驱动 链表自动驱动
Sleep(1);          // 周期1ms
```
